Style/SymbolArray:
  EnforcedStyle: brackets
Style/Documentation:
  Enabled: false
Layout/TrailingWhitespace:
  Enabled: false
Metrics/LineLength:
  Max: 100
Style/NumericLiterals:
  Enabled: false
Style/MixinUsage:
  Enabled: false
Lint/ParenthesesAsGroupedExpression:
  Enabled: false
Metrics/BlockLength:
  Enabled: false