sut:
  build: .
  environment:
    RAILS_ENV: test
  command:
    - bin/test.sh
  links:
    - web
web:
  build: .
  command: puma
  links:
    - postgres
  ports:
    - "8080:8080"
postgres:
  image: postgres